import type { Metadata } from "next";
import { Lato, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import clsx from 'clsx';


const lato = Lato({
  subsets: ['latin'],
  weight: ['100','300','400','700'],
  variable: '--font-lato',
});

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: ['200','300', '400', '700'],
  variable: "--font-source-serif"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={clsx(sourceSerif.variable, lato.variable)}
      >
        {children}
      </body>
    </html>
  );
}
