import type { Metadata } from "next";
import "./globals.css";
import { Mulish, Roboto } from 'next/font/google'
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';

const lucidaGrande = localFont({
  src: '../fonts/LucidaGrande.ttf',
  
  variable: '--font-lucida',
});



// Importing fonts from Google and local sources

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-poppins',
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.variable}  `}
      >
        
        {children}
      </body>
    </html>
  );
}
