import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";



const roboto_custom = Roboto({
  subsets: ['latin'],
  weight: ['100','300','400','700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto_custom.variable}
      >
        {children}
      </body>
    </html>
  );
}
